### PR TITLE
Added POD_MEMORY_SIZE as a configurable value

### PR DESCRIPTION
**Pull request by mikepc**

### CODE REVIEW

**Comment by erez-rabih** [comment]
Hi thanks for the PR
I would like to merge but I think the environment variable could be better - maybe `POD_MEMORY_REQUEST` ?
I'm saying that thinking of the future when someone else would need to add memory limit and even cpu requests/limits

**Review by erez-rabih — CHANGES_REQUESTED** [review]
please review the environment variable name

**Comment by mikepc** [comment]
I'll update this tonight!

**Comment by daanl** [comment]
Hi, would it be possible to merge it? 5GB seems way to much for simpel cluster :-)

**Review by erez-rabih — APPROVED** [review]

**Pull request merged**
