### PR TITLE
Support for defining a namespace in kubernetes

### PR DESCRIPTION
**Pull request by dggc**
This pull request enables defining a workspace to create the rabbitmq cluster on.

### CODE REVIEW

**Review by erez-rabih — CHANGES_REQUESTED** [review]
Thanks for the PR, two questions/requests before I merge this:
1. Have you tested it on an actual K8s cluster?
2. Please update the readme also on the environment variables table explaining what each variable means.

**Comment by dggc** [comment]
@erez-rabih I've updated the the table with the description of the variable.

I've tested it in a Minikube Kubernetes cluster, and it was correctly created. I believe it would work the same way in an AWS cluster

**Comment by erez-rabih** [comment]
@dggc Thanks for that

Another issue that crossed my mind:

You should create the namespace if it does not exist. Something like
```
kubectl get ns $(NAMESPACE) || kubectl create ns $(NAMESPACE)
```
In the Makefile

Also, please mention it in the Environment variables table: if the namespace does not exist in the moment of deployment, it will be created for you.

**Comment by erez-rabih** [comment]
👍  Great!

**Review by erez-rabih — APPROVED** [review]

**Comment by dggc** [comment]
@erez-rabih true, it is important to create the namespace if necessary. Just did it

**Comment by erez-rabih** [comment]
@dggc Already merged

**Pull request merged**
